# stationTypes
# A list of the names of crafting station types that this recipe can be made from. Most items can
# only be crafted from one station type, but some can be crafted from multiple types, such as being
# able to make basic potions at both a mortar & pestle, and at a laboratory.

# stats
# Optional. A list of the names of stats that will be used in the crafting of this item.
# Uses the average level of all of the given stats (rounded down) when calculating the crafting bonus.
# e.g. If 2 stats are given, one of level 5 and one of level 10, the stat level crafting bonus will be 7.
# Divides the exp received among all of the given stats (rounded down).
# e.g. If 3 stats are given, and the total exp given by crafting this item is 100, then each stat will gain 33 exp.

# expGiven
# Optional. A specific amount of exp given for crafting this item. Default will use the sum of the craftingExpValues of each ingredient.

# ingredients
# A list of the items required to craft this item. The order here is the order they will be shown in the GUI crafting panel.
#   itemName
# The type/class name of the ingredient.
#   quantity
# How many of the ingredient type are required.

# result
# The item that will be crafted by this recipe.
#   itemName
# The type/class name of the item.
#   baseQuantity
# Optional. How many of item will be crafted. Stackables only. Increases with the level of the stats given in the stats list.
# If not specified, the baseQuantity from the item values config will be used as the default.
#   baseDurability
# Optional. How much durability the item will have. Unstackables only. Increases with the level of the stats given in the stats list.
# If not specified, the baseDurability from the item values config will be used as the default.


# Materials


# Potions


# Iron equipment

- stationTypes:
  - Anvil
  stats:
  - Weaponry
  - Melee
  ingredients:
  - itemName: IronBar
    quantity: 1
  - itemName: OakLogs
    quantity: 2
  - itemName: Feathers
    quantity: 1
  result:
    itemName: IronArrows
    baseQuantity: 20

# Dungium equipment

- stationTypes:
  - Anvil
  stats:
  - Weaponry
  - Melee
  expGiven: 123
  ingredients:
  - itemName: DungiumBar
    quantity: 5
  result:
    itemName: DungiumSword

- stationTypes:
  - Anvil
  stats:
  - Weaponry
  - Melee
  ingredients:
  - itemName: DungiumBar
    quantity: 1
  - itemName: OakLogs
    quantity: 2
  - itemName: Feathers
    quantity: 1
  result:
    itemName: DungiumArrows
    baseQuantity: 20

# Noctis equipment


# Ranged equipment


# Mage equipment

