
# Arrows

- name: IronArrow
  moveRate: 100
  range: 8
  damageAmount: 14
  damageTypes:
    - Physical
  damageArmourPiercing: 15

- name: DungiumArrow
  moveRate: 100
  range: 8
  damageAmount: 16
  damageTypes:
    - Physical
  damageArmourPiercing: 20
  
- name: AgoniteArrow
  moveRate: 100
  range: 8
  damageAmount: 18
  damageTypes:
    - Physical
  damageArmourPiercing: 25

- name: NoctisArrow
  moveRate: 100
  range: 8
  damageAmount: 20
  damageTypes:
    - Physical
  damageArmourPiercing: 30

# Shurikens

- name: Shuriken
  moveRate: 150
  range: 4
  damageAmount: 20
  damageTypes:
    - Physical

# Daggers

- name: IronDagger
  moveRate: 200
  range: 1
  hasBackStabBonus: true
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical

- name: DungiumDagger
  moveRate: 200
  range: 1
  hasBackStabBonus: true
  collisionType: Melee
  damageAmount: 9
  damageTypes:
    - Physical

- name: AgoniteDagger
  moveRate: 200
  range: 1
  hasBackStabBonus: true
  collisionType: Melee
  damageAmount: 10
  damageTypes:
    - Physical

- name: NoctisDagger
  moveRate: 200
  range: 1
  hasBackStabBonus: true
  collisionType: Melee
  damageAmount: 11
  damageTypes:
    - Physical

# Swords

- name: IronSword
  moveRate: 200
  range: 3
  collisionType: Melee
  damageAmount: 20
  damageTypes:
    - Physical

- name: DungiumSword
  moveRate: 200
  range: 3
  collisionType: Melee
  damageAmount: 24
  damageTypes:
    - Physical

- name: AgoniteSword
  moveRate: 200
  range: 3
  collisionType: Melee
  damageAmount: 28
  damageTypes:
    - Physical

- name: NoctisSword
  moveRate: 200
  range: 3
  collisionType: Melee
  damageAmount: 32
  damageTypes:
    - Physical

# Hammers

- name: IronHammer
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 20
  damageTypes:
    - Physical

- name: DungiumHammer
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 24
  damageTypes:
    - Physical

- name: AgoniteHammer
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 28
  damageTypes:
    - Physical

- name: NoctisHammer
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 32
  damageTypes:
    - Physical

- name: HammerOfGlory
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 32
  damageTypes:
    - Physical

# Hatchets

- name: BoneHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 6
  damageTypes:
    - Physical

- name: IronHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical

- name: DungiumHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 9
  damageTypes:
    - Physical

- name: AgoniteHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 10
  damageTypes:
    - Physical

- name: NoctisHatchet
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 11
  damageTypes:
    - Physical

# Pickaxes

- name: BonePickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 6
  damageTypes:
    - Physical

- name: IronPickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical

- name: DungiumPickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 9
  damageTypes:
    - Physical

- name: AgonitePickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 10
  damageTypes:
    - Physical

- name: NoctisPickaxe
  moveRate: 500
  range: 2
  collisionType: Melee
  damageAmount: 11
  damageTypes:
    - Physical

# Sickles

- name: IronSickle
  moveRate: 500
  range: 1
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical

- name: DungiumSickle
  moveRate: 500
  range: 1
  collisionType: Melee
  damageAmount: 9
  damageTypes:
    - Physical

- name: AgoniteSickle
  moveRate: 500
  range: 1
  collisionType: Melee
  damageAmount: 10
  damageTypes:
    - Physical

- name: NoctisSickle
  moveRate: 500
  range: 1
  collisionType: Melee
  damageAmount: 11
  damageTypes:
    - Physical

# Magic

- name: Wind
  moveRate: 200
  range: 6
  damageAmount: 6
  damageTypes:
    - Magical

- name: SuperWind
  moveRate: 200
  range: 7
  damageAmount: 6
  damageTypes:
    - Magical

- name: Fire
  moveRate: 200
  range: 6

- name: SuperFire
  moveRate: 200
  range: 7

- name: BloodBolt
  moveRate: 200
  range: 6
  damageAmount: 20
  damageTypes:
    - Magical
    - Biological
  healAmount: 20

- name: SuperBloodBolt
  moveRate: 200
  range: 7
  damageAmount: 20
  damageTypes:
    - Magical
    - Biological
  healAmount: 20

- name: Deathbind
  moveRate: 200
  range: 6

- name: Pacify
  moveRate: 200
  range: 6

# Misc

- name: WoodenClub
  moveRate: 200
  range: 2
  collisionType: Melee
  damageAmount: 8
  damageTypes:
    - Physical

- name: Acorn
  moveRate: 200
  range: 6
  damageAmount: 16
  damageTypes:
    - Physical

- name: Snowball
  moveRate: 200
  range: 4
  damageAmount: 8
  damageTypes:
    - Physical

- name: Dark
  moveRate: 100
  range: 7
  damageAmount: 20
  damageTypes:
    - Magical

- name: VampireFang
  moveRate: 200
  range: 1
  collisionType: Melee
  damageAmount: 20
  damageTypes:
    - Physical
    - Biological
